version: '3.5'
services:
  my-docker-service:
    image: elenas-image
    ports:
      - ${APP_PORT}:8005
    build:
      context: .
      dockerfile: Dockerfile
    image: elenas-app:latest
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    container_name: elenas-container


networks:
  default:
    name: my_network
    external: False
    