version: '3.8'
services:
  my-docker-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: elenas-app:latest
    ports:
      - ${APP_PORT}:8005
    env_file:
      - .env
    container_name: elenas-container

networks:
  default:
    name: my_network
    external: false
    